### ISSUE TITLE
Add ability to save/restore placement for a specific app

### ISSUE THREAD

**Issue by eruure** [eczarny/spectacle#255]
I love the various options Spectacle has, but I miss the ability to set my placement to exactly the position I want. 
What would be handy are two additional shortcuts, one which would save the current placement of the window, and another that would restore it. I don't know what's possible on Mac, but I hope detecting the name of the app a window belongs to is possible - then one could remember that placement with the app name. 
And ideally,  this would be also bound to the physical resolution of the entire screen, such that one could have different settings for different monitors.

**Comment by nightwolfzor** [comment]
+1

**Comment by narlei** [comment]
+1

**Comment by meakl** [comment]
+1

**Comment by filipebarcos** [comment]
:+1:

**Comment by thrawn01** [comment]
+1

**Comment by guillaumesalagnac** [comment]
+1

**Comment by jeberly** [comment]
+1 for just restoring windows to their last placement location on specific display setups, eg (using external monitor or not)

**Comment by ntrepid8** [comment]
I've used a similar feature in the Gnome3 desktop called [put-windows](https://extensions.gnome.org/extension/39/put-windows/).  It supports the ability to define a set of positions for an application and them you can use a shortcut key to move the app to the "next" defined position.  The user can then continue to press the shortcut key to cycle through all the defined positions.

Is that the sort of functionality that people are looking for here?  If that's correct, I may take a swing at implementing it because I would like the same sort of thing on my Mac.

**Comment by eczarny** [comment]
Unfortunately this isn't something I would like to support. Perhaps somebody could build something like this once #427 is added. Folks wanting to have an app remember where their windows are with external displays should look at Stay (https://cordlessdog.com/stay/).
