### ISSUE TITLE
Toggle fullscreen / Undo with same keystroke

### ISSUE THREAD

**Issue by zanona** [eczarny/spectacle#284]
Hey Eric, really loving spectacle here. Thanks so much.
One thing I would find it very useful is that when going full screen, that usually happens for a while and at some point I always like to restore the window dimensions to its previous configuration. Said that, it would be great if when going fullscreen, when the same keystroke is used again, it would then return the window to its previous dimensions. 
This way a new use could be given to the same keystroke, considering that currently, when full screen is achieved the keystroke is discarded when it is already in that mode.

**Comment by eczarny** [comment]
Interesting! Thanks for clarifying. Sounds like an potential enhancement.

**Comment by duanefields** [comment]
Or if nothing else, if you are in native full screen mode, and I tell spectacle that I want the window in any non full screen layout (Right Half for example) then it should drop out of full screen and do so. As is, in full screen mode spectacle doesn't do anything. I hit this use case every day because I switch my editor between a laptop (where I run full screen) and my iMac (where I run 2-up)

**Comment by eczarny** [comment]
Unfortunately this isn't a feature I plan to build or support. Closing this out.
