### ISSUE TITLE
Feature request: Push application to a corner of the screen.

### ISSUE THREAD

**Issue by wavded** [eczarny/spectacle#299]
First off, thanks for your hard work on this app.  It is a lifesaver.

Secondly, it would be really useful for me and hopefully others to be able to push an app to a corner *without* resizing it.  I typically want to keep the size of my windows (like terminal or editor or whatnot) but just want them in their own area of the screen.

**Comment by erchn** [comment]
+1

**Comment by jonathanPoitz** [comment]
+1 I was missing a similar feature, my idea was to push windows to the edge of the window, but the corners certainly would be a good idea as well.

**Comment by denys-lysiuk** [comment]
+1

**Comment by joshtronic** [comment]
:+1:

**Comment by guillaumesalagnac** [comment]
+1

**Comment by eczarny** [comment]
Closing in favor of #410.

**Comment by shamrin** [comment]
@eczarny Why do you prefer #410 move-around feature instead of push-to-corner feature (this issue)? We already have a perfect (and accurate!) tool for moving windows around - mouse/trackpad. But snapping window to corner is harder with trackpad. I usually have to do "Upper Right" or "Right Half" command and then resize the window with the trackpad. What is your rationale?

P.S. Thank you for a great work! Spectacle is wonderful.
