### ISSUE TITLE
No works in Yosemite 10.10.1

### ISSUE THREAD

**Issue by wilfredosh** [eczarny/spectacle#307]
I'm trying to use this in Yosemite 10.10.1 version and It is not working...
Thanks for your help

**Comment by df-andrews** [comment]
I've been using this in Yosemite 10.10.1 for a while now with no issues. 
Have you enabled it in System Preferences -> Security and Privacy -> Accessibility ?

**Comment by wilfredosh** [comment]
I can right now... so you can check apps like Microsoft Remote Desktop: https://itunes.apple.com/en/app/microsoft-remote-desktop/id715768417?mt=12

It's working for apps like Safari, Skype, etc but not for this app example.

Thanks for your answer!

**Comment by davetcoleman** [comment]
Just installed this on a fresh install of Yosemite and it works great, thanks so much!

**Comment by urda** [comment]
Spectacle working fine over here.

```
System Version:   OS X 10.10.1 (14B25)
Kernel Version:   Darwin 14.0.0

Spectacle - Version 0.8.8 (395)
```

**Comment by prestia** [comment]
Spectacle runs in Yosemite, but I have had issues with it ever since the update to 10.10. Specifically, the 2/3 window sizing doesn't seem to work in a number of Apple applications. For example, when hitting ⌥⌘← or ⌥⌘→, Safari 8 and Mail 8 alternate between 1/2 and 1/3 of the screen (but never 2/3). Other applications (like TextEdit) are unaffected.

Anyone else experiencing this?

**Comment by eczarny** [comment]
@prestia That can be a problem if the windows have had their dimensions restricted. A good way to verify this behavior is to try and shrink the windows manually yourself. If you can't make them fit into the 2/3 size odds are Spectacle can't either.

I'm closing this issue but feel free to open a new one if what I mentioned is not the case.
