### ISSUE TITLE
Do not work on Yosemite

### ISSUE THREAD

**Issue by G4BB3R** [eczarny/spectacle#331]
Seems to not work on Yosemite system.
I installed and none shortcut makes anything :(

**Comment by jeroenkruis** [comment]
Works fine for me. Have you tried installing it using brew?
```bash
$ brew cask install spectacle
```

I'm on Yosemite 10.10.2

**Comment by G4BB3R** [comment]
Thanks for the reply, but cask command is unknown here, but brew-only-commands works.
How can I solve this ?
http://i.imgur.com/6KSIgwZ.png

**Comment by jeroenkruis** [comment]
My bad, should've told you how to install [Homebrew Cask](http://caskroom.io/) in the first place. Homebrew Cask is most of the time abbreviated as Cask, just so you know.

1. First install Cask

  ```bash
  $ brew install cask
  ```

2. Install Spectacle through Cask

  ```bash
  $ brew cask install spectacle
  ```

3. Cask should symlink Spectacle for you. Which means you can find it in the applications folder in finder or use `⌘ + Space` and look up Spectacle.

You might want to read more about [Homebrew Cask](http://caskroom.io/) and how it works because it really is a great tool, it made installing applications on a Mac alot easier.

Let me know if it works.

**Comment by G4BB3R** [comment]
Damn me! Thanks, it worked :D :+1:
