### ISSUE TITLE
Window not covering the full window, and problems with make smaller

### ISSUE THREAD

**Issue by arianmaykon** [eczarny/spectacle#379]
When resizing the iTerm2 window to half-screen, on a external monitor, the screen does not cover all the screen, a few pixels lines are missing on top or bottom, even in fullscreen, and when i put the iTerm2 window on half screen and try to resize it down horizontally (Make Smaller shortcut) the windows are resized vertically too. But i've noticed that if i resize the window manually to a almost monitor fit (vertically), the make smaller/greater is working again, making the windows smaller/greater only horizontally.

FYI, this was not happening a few weeks ago, i don't know if it was the Spectacle or iTerm2 update (or other thing) that introduced this behavior.

Spectacle version: 0.8.10
iTerm2 version: 2.0.0.20150412
OSX: 10.10.3

Thanks for this great software.

**Comment by arianmaykon** [comment]
If helps the detection, seems like the problem only occurs when theres only one tab in the iTerm2 window.

**Comment by nicolas-martin** [comment]
Yes I'm having the same behaviour.

**Comment by eczarny** [comment]
With apps like iTerm Spectacle has to work around size restrictions those apps put on their windows. In terminal emulators the typical behavior (in Terminal and iTerm) is to force window sizes to match whole rows and columns. To learn more about what Spectacle is doing check out #250.

What you are seeing is Spectacle following this behavior to resize the iTerm window to fit into the area of the screen you want. Unfortunately this can make resizing the window using the "Make Larger" and "Make Smaller" shortcuts a bit more awkward. Since the edges of the windows are not touching the edges of the screen Spectacle will not ensure they remain in contact.

**Comment by arashsa** [comment]
I'm having this problem too, any solutions?
