### ISSUE TITLE
Shortcuts using Fn should only be allowed where it makes sense (e.g. to use F1)

### ISSUE THREAD

**Issue by krisdestruction** [eczarny/spectacle#382]
I'm using a hotkey such as "Fn + Left". However the keyboard captured for the hotkeys don't appear correctly when the Fn modifier is used. Is it possible to add "Fn" to display the modifier?

Here is a screenshot of my configuration. To exemplify, "Fn + Left" shows as a blank for "Left Half".
![screen shot 2015-04-27 at 7 35 27 pm](https://cloud.githubusercontent.com/assets/1440068/7360087/b8883b6e-ed14-11e4-8274-15154611203c.png)

**Comment by mike-joyce** [comment]
I'm having exactly the same problem.

**Comment by eczarny** [comment]
To be honest I actually think this behavior is correct. The Fn key is not a modifier and I don't believe it should be displayed. In a quick test I tried to see how Apple's keyboard shortcut preferences treated the Fn key when changing the Spotlight shortcut. In the test the Fn key was never displayed.

The actual issue here is that you were allowed to use Fn and an arrow key as a shortcut in the first place.

**Comment by krisdestruction** [comment]
The other modifier keys are bound to other things on my keyboard and thus the Fn key is the best key to use with my setup. Perhaps you should consider this as an extra feature as this app is clearly made to complement features that are lacking on OSX. However, I can't imagine it being too hard to add. If so, please consider this a feature request.
