### ISSUE TITLE
Spectacle fails to work on Microsoft Word 2016 (Preview) for Mac v15.11

### ISSUE THREAD

**Issue by pmgower** [eczarny/spectacle#408]
Yesterday I upgraded to the latest version of Microsoft Word 2016 (Preview) (v15.11 (150609)) and prior to that update I was able to use spectacle to resize and move my MS Word windows.  However now when I do it I just get an audible "beep" and the window doesn't move or do anything.  When I updated MS Word I also updated MS PowerPoint and it still works with Spectacle.

**Comment by DuncanSmith** [comment]
Same happening with me after the update. I'm now running MS Word 2016 Preview for Mac, version 15.11.1 (150618).

All the other office apps, (PowerPoint, Excel, Outlook) seem to work ok despite being on the same version.

**Comment by JC713** [comment]
Oh yeah after the 15.11 update, I am also having this issue! 15.11.1 did not fix it either. This is not an issue with PPT or Excel by the way.

I had this issue with MS PPT in the past (a very early 2016 preview version) and I reported it via the bug reporter. It was fixed in the following update. I did the same this time with 15.11.1. Hopefully they fix it if Eric can't. I wonder if it is an issue with Spectacle or with Word itself.

Thanks.

**Comment by kolunkung** [comment]
In 15.11 it seems the key combo command + option + left/right arrow are assigned to WebGoBack and WebGoForward.  Sadly, it's not possible to remove them in the "Customized Keyboard..." because they simply do not exist in  "All commands" or any other categories.

**Comment by JC713** [comment]
This issue can be closed because 15.11.2 (release version to Office 365 customers) fixes the problem.
