### ISSUE TITLE
[Feature Request] - Divide Active Windows Equally Side-by-side

### ISSUE THREAD

**Issue by zulhfreelancer** [eczarny/spectacle#411]
I always put Sublime Text on left side and keep my Chrome browser on the right side. It would be nice if Spectacle can merge "Left Half" and "Right Half" command into 1 new single command which will divide active windows (Sublime Text & Chrome) equally half, side-by-side like so:

![screen shot 2015-06-23 at 5 02 17 am](https://cloud.githubusercontent.com/assets/3416976/8292901/98f865fe-1964-11e5-9b3c-8a684a03c739.png)

Thanks.

**Comment by kokarn** [comment]
How would you define the "active windows"?

**Comment by zulhfreelancer** [comment]
Active windows = Sublime Text and Chrome (or any browser).

**Comment by kokarn** [comment]
How is the program to know what you think is the active windows? Always
Sublime and a browser? Seems a bit specific.

**Comment by zulhfreelancer** [comment]
I would say that the "active windows" is all windows that are not minimize.

**Comment by eczarny** [comment]
It probably wouldn't be very obvious to most folks how a shortcut like this would work. Knowing which windows are minimized or hidden is a bit difficult (I know I usually have no idea what state my windows are in).

I'm going to close this issue out in favor of #255. Instead of just saving a window layout for a specific app what about if Spectacle allowed you to save a window layout for a set of apps? There are still a lot of edge cases to be sorted out but I think it should accomplish what you are asking for here.
