### ISSUE TITLE
fn key not recorded for undo command shortcut

### ISSUE THREAD

**Issue by zanona** [eczarny/spectacle#418]
it seems when setting the shortcut for the command _Undo_ to:

<kbd>fn</kbd><kbd>control</kbd><kbd>Z</kbd>

<kbd>fn</kbd> is ignored and by simply pressing <kbd>control</kbd><kbd>Z</kbd> already triggers the _Undo_ action.

**Comment by eczarny** [comment]
From my understanding the <kbd>fn</kbd> key is only really useful when you wish to use a key combined with another on compact keyboards. It really wouldn't have any affect on the <kbd>control</kbd> key since it isn't a combined key. On the other hand it does allow you to use a function key (e.g. <kbd>F1</kbd>).

**Comment by zanona** [comment]
that odd because I do use fn+control+arrow keys to align 50% left and right
and for those I had no problems?

**Comment by eczarny** [comment]
That's because they are combined keys:

https://support.apple.com/en-us/HT201236

**Comment by zanona** [comment]
Thanks for the link @eczarny. I think I understand now. :+1:
