### ISSUE TITLE
Spectacle version 1.0 fails to work with Microsoft Word 2011

### ISSUE THREAD

**Issue by evam70** [eczarny/spectacle#447]
Hi, 
I have just updated Spectacle to version 1.0 and now Spectacle is not working with Microsoft Word. MW does not respond to keyboard shortcuts or clicking on Spectacle options. 

Thanks

**Comment by weitzj** [comment]
The same with Quicksilver (http://qsapp.com). Maybe even with Mac System Preferences itself.

**Comment by eczarny** [comment]
What windows would you want to move in either Quicksilver or System Preferences?

Microsoft is notorious for building out their applications in a way that aren't completely compatible with Spectacle. There is typically little I can do in that case. I am curious though, what happens if you restart your computer?

**Comment by weitzj** [comment]
> What windows would you want to move in either Quicksilver or System Preferences?

The quicksilver launcher window. I would like to center it with my center shortcut. I have to center it fairly often since I have two external displays plugged into my MacbookPro and sometimes the quicksilver window takes the center coordinates of the laptop display, which is different from the external displays and vice versa.
I rolled back to 0.8.10 on 10.10.4 where everything works fine.

**Comment by evam70** [comment]
Hi, 

I have restarted the computer but Spectacle is still not working with Word. Any solution? I would not like to stop using Spectacle for that reason. It´s a great app. Before the update it was working ok. 

Thanks

**Comment by jaapwalhout** [comment]
I had the same issue with MS Word. After downgrading to 0.8.10, Spectacle worked again. So, it probably has something to do with changes in the 1.0 version.

**Comment by evam70** [comment]
Yes, I have just downgrading to 0.8.8 and it is working.
Thanks, Jaap. We will have to wait to next 1. versions to fix the issue.

**Comment by eczarny** [comment]
Interestingly I have no trouble with Spectacle 1.0 and Microsoft Word 2011. I have OS X10.10.5 installed with Microsoft Word for Mac 2011 Version 14.5.4 (150722).

It would be helpful if somebody experiencing issues could provide Console output.

**Comment by jaapwalhout** [comment]
@eczarny Could it be that the version of Word is the problem? I have 14.1.0

**Comment by eczarny** [comment]
It's very possible. Can you upgrade and verify?

**Comment by jaapwalhout** [comment]
after updating to 14.5.4, I don't have this issue anymore

**Comment by eczarny** [comment]
:+1:

In that case I'm closing this issue. Sounds like Microsoft fixed things.
