### ISSUE TITLE
Feature: Profiles

### ISSUE THREAD

**Issue by poyannabati** [eczarny/spectacle#523]
I have an external keyboard and have mapped Spectacle to use some of the keys on the numeric keypad. Most of the time I'm using the external keyboard, but once in a while I disconnect and use the internal keyboard. 

There should be a setting to quickly switch between different "profiles", i.e., mappings of keyboard shortcuts to solve this situation. Shouldn't be too difficult to implement. What do you think?

**Comment by exalted** [comment]
Personally feels like an issue on user’s side more than something that this app should manage on its own.

My argument is that this problem remains unsolved for any app (even Apple’s own apps, such as Safari, Notes, Calendar, etc.) and AFAIAC the solution shouldn’t be solved by every single app internally.

**Comment by eczarny** [comment]
@exalted that's a good point. Odds are I won't likely get around to even implementing this enhancement so I'm going to close it out.

**Comment by exalted** [comment]
:clap:

**Comment by caseyWebb** [comment]
I don't know a line of Objective-C, but I'm willing to try to learn to make this happen with a PR.

I leave my laptop plugged in at work to an external display and keyboard, and as @poyannabati I mapped the shortcuts to the numpad because it's available. However, since doing so Spectacle is useless once I head home.

IMHO Apple's apps are mediocre at best, whereas Spectacle is a power-user app — not to mention one whose entire purpose is to provide keyboard shortcuts. It doesn't seem fair to reject the idea entirely based on what Apple does or does not do.
