### ISSUE TITLE
1.0.5 - Overwriting shortcuts after upgrade, specifically lower/upper/half right/left

### ISSUE THREAD

**Issue by akamike** [eczarny/spectacle#578]
Just updated to 1.0.5 and found some of the shortcuts have been muddled up, six of which are now assigned to ⇧← and ⇧→ (very confusing when selecting text). See attached screenshot of preferences screen:

![spectacle-prefs](https://cloud.githubusercontent.com/assets/95465/14983561/1371b80c-1136-11e6-9b1b-8c206838e140.png)

This was not what I had set previously, and isn't using the defaults suggested in the README. However, even after restoring the preferences file from a backup it keeps being overwritten and setting to these keys. Setting preferences manually or restoring defaults (via the provided button) seems to save correctly, but I imagine this would be frustrating for anyone with significant customisation.

OS X version: 10.11.3

Possibly related to #568 though that was the previous version and looks like restoring from a backup worked, where as it does not here.

**Comment by richard-mansfield** [comment]
I also find the assigned to ⇧← and ⇧→, up and down, very confusing when selecting text.  I suggest the default keyboard shortcuts for these should be shift + option + command + cursor.

**Comment by eczarny** [comment]
@richard-mansfield Those are not the intended default shortcuts for those window actions. This issue is tracking a bug where Spectacle accidentally overwrites the configured shortcuts.

As a workaround quit Spectacle, delete `~/Library/Preferences/com.divisiblebyzero.Spectacle.plist`, and launch Spectacle again. This is completely restore Spectacle to its defaults. Rebooting may also help.

I'm working on overhauling how Spectacle stores these keyboard shortcuts to prevent issues like this from happening in the future.
