### ISSUE TITLE
Support for predefined sizes

### ISSUE THREAD

**Issue by exalted** [eczarny/spectacle#610]
I wish there was a way to resize any window to a predefined size.

This could be as simple as _one_ prefined size available in the menu, or a list of sizes which users could map to whatever keyboard shortcuts they’d like to.

Often times I find my self to resize my windows to a specific size that I like when I am on my external display which is not either half or third of my display (vertically or horizontally).

What do you think?

**Comment by bzx** [comment]
It would be great to have it! 

Here's how Breeze app did it (which I am currently using instead of Spectacle), and perhaps Spectacle could achieve this in a similar way. 

<img width="549" alt="screen shot 2016-06-23 at 10 57 44" src="https://cloud.githubusercontent.com/assets/654500/16297485/5488d9c4-3931-11e6-8a92-428ff2b1556a.png">

**Comment by exalted** [comment]
@eczarny as in "not interested"?

**Comment by eczarny** [comment]
@exalted correct. Other apps already do this and I have no plans to have Spectacle support the same behavior.

**Comment by bzx** [comment]
that's a pity
