### ISSUE TITLE
Messages app will only go in the first third

### ISSUE THREAD

**Issue by wturrell** [eczarny/spectacle#620]
Pressing `ctrl + opt + right` the first time makes Messages full height in the first (left) third, as you'd expect. But on subsequent presses it appears to be stuck - the window looks like it's about to move then snaps back to the left again.

Thanks,
William

**Comment by eczarny** [comment]
This is likely due to the fact Spectacle cannot make the the window fit into a third of the display. On a larger display this would probably work. Check out this part of the README for a bit more information:

https://github.com/eczarny/spectacle#spectacle-does-not-resize-a-particular-window-as-expected
