### ISSUE TITLE
Fullscreen Alt+Cmd+F does not work as expected

### ISSUE THREAD

**Issue by MikhailTestov** [eczarny/spectacle#647]
Spectacle 1.1 (648)
OS X El Capitan 10.11.6 on MB Pro 15" Mid 2015
No output in console

Fullscreen behave strange for most of the windows. For example: Evernote, Safari, IntelliJ IDEA, FireFox, iTerm2 and others. But for Console app works as expected.

When pressing Alt+Cmd+F, left upper corner remains on it's position, but right bottom corner position moves to the right bottom corner of the screen. Second Alt+Cmd+F  will move whole window to the centre of the screen without any size changes. 3rd one will work as 1st one. And so on. So to resize to fullscreen I need several iterations.

Other features works as expected without any issues.

**Comment by eczarny** [comment]
@MikhailTestov mind sharing a screenshot or a video?

**Comment by MikhailTestov** [comment]
@eczarny sure, take a look:
![screen shot 2016-09-14 at 18 37 50](https://cloud.githubusercontent.com/assets/10000666/18518959/baf670c6-7aaa-11e6-85fa-4173e62ba6c7.png)
![screen shot 2016-09-14 at 18 38 30](https://cloud.githubusercontent.com/assets/10000666/18518957/baf32556-7aaa-11e6-9c0b-613fa8069c22.png)
![screen shot 2016-09-14 at 18 38 53](https://cloud.githubusercontent.com/assets/10000666/18518958/baf56ece-7aaa-11e6-8d3f-f9a9e8fa7c6d.png)
![screen shot 2016-09-14 at 18 39 18](https://cloud.githubusercontent.com/assets/10000666/18518956/baf32290-7aaa-11e6-8d1d-193ebda93c56.png)
![screen shot 2016-09-14 at 18 39 46](https://cloud.githubusercontent.com/assets/10000666/18518955/baebdff8-7aaa-11e6-9ef3-4502743a490e.png)

And so on ...

**Comment by eczarny** [comment]
@MikhailTestov Thanks for the screenshots! does rebooting help at all? Have you tried restarting Spectacle?

**Comment by MikhailTestov** [comment]
Eric,

Even upgrading to version 1.1 doesn't help and macOS Sierra GM candidate didn't. 



Mikhail

**Comment by m99coder** [comment]
A lot of the shortcuts used by Spectacle are not recognized anymore if you have a keyboard attached to a laptop. For instance Ctrl+Cmd+F for Fullscreen in Chrome leads to a shortcut inside of address bar to search something. Are there any known issues with an attached keyboard under macOS Sierra?

**Comment by eczarny** [comment]
@m99coder first I've heard of that behavior. Mind opening a separate issue to track it?

**Comment by m99coder** [comment]
I will make a second test run as soon as I’m back in office after vacation. If I can reproduce this behavior I will open a separate issue as you suggest.

**Comment by FernandoMiguel** [comment]
having the same issue as @m99coder 
after rebooting today to upgrade sierra 10.12.1b and to the latest chrome dev, cmd+alt+F is no longer maximizing chrome :(

**Comment by m99coder** [comment]
I actually don’t have the issue anymore. Maybe it was a side effect of something else already fixed?

**Comment by eczarny** [comment]
@MikhailTestov are you still running into this problem?

**Comment by havardge** [comment]
I have a very similar issue using Spectacle (10.14.2) to resize Firefox (64.0.2) on macOS Mojave (10.14.2). The window is gradually increasing in size as I repeat pressing the full screen shortcut. Slack behaves in a similar way (slightly less predictable). Previously I used SizeUp from Irradiated Software (closed source, not free), it had the exact same issues with Firefox and Slack (using the same versions as stated above).

One thing I've noticed is with Firefox and Slack, these applications does not simply _set_ the new window sizes and then redraw, they (in lack of a better description) _transition into_ the new size, doing multiple redraws in the process. I find that applications who simply accepts the new window size, then redraws once behave as expected with Spectacle.  

As opposed to @MikhailTestov, IntelliJ IDEA, Safari, iTerm2 works fine for me.

I'm not even sure if this can be fixed in Spectacle, but maybe someone would like to have a look at this. If Specatcle produces any logs / debug info I'd be happy to provide it.
