### ISSUE TITLE
Full screen shortcut leaves a small gap between the window and Dock when the Dock is set on either side

### ISSUE THREAD

**Issue by alvarosevilla95** [eczarny/spectacle#680]
Having the dock on the right (or left) side of the screen, and using the full screen shortcut leaves a small gap between the window and the Dock. This doesn't happen when using the shortcut to move to the half where the Dock is.

Using Right Half shortcut:
<img width="62" alt="screen shot 2016-11-26 at 12 57 21 pm" src="https://cloud.githubusercontent.com/assets/1376447/20640203/f401c7b0-b3d7-11e6-8dda-5bfd282aa654.png">

Using Full Screen shortcut:
<img width="62" alt="screen shot 2016-11-26 at 12 57 12 pm" src="https://cloud.githubusercontent.com/assets/1376447/20640204/f7d383ec-b3d7-11e6-9cd5-034062bf22dd.png">

**Comment by ttben** [comment]
Yep ! I confirm that!
I thought this was only me..

**Comment by eczarny** [comment]
I investigated this a bit and it looks like the result of rounding in the window calculations. My guess is folks with different display resolutions may or may not see this discrepancy.

**Comment by worriorbg** [comment]
@alvarosevilla95 and @ttben I might have found a workaround for this issue that introduces one additional move to the left (a bit of jiggle) but did fix a similar issue I saw. 
Let me know if you want to try test build to see if it fixes your problem too.

**Comment by lacostenycoder** [comment]
I have similar issue but not related to dock.  I use ITerm in full screen often with multiple tabs etc.  If is resize Iterm by hand or with Spectacle, it doesn't cover the full screen.  But for some reason only on Iterm.  The only way to get it back to where it's not in weird 98% fill is to close all tabs / windows and launch a new one.  In first image, it's subtle but annoying because I use a dark window, light background shows at bottom and sometimes sides.  Playing with Iterm settings has no effect on Spectacle behavior.  

After Spectacle full screen: 
![screen shot 2017-04-05 at 4 07 35 pm](https://cloud.githubusercontent.com/assets/6077905/24724946/0f79bf4e-1a1b-11e7-9403-45c009d09f48.jpg)

Fresh launch Iterm before ever using Spectacle full screen:
![screen shot 2017-04-05 at 4 12 03 pm](https://cloud.githubusercontent.com/assets/6077905/24725213/f528b644-1a1b-11e7-8730-8fe11777695b.jpg)

**Comment by jeffalexander** [comment]
From some Google searching, the dock reserving 5 or so pixels has been around for a long time.

@worriorbg I would like to test your fix.

**Comment by jakeonrails** [comment]
@lacostenycoder https://github.com/eczarny/spectacle/issues/280#issuecomment-236540753 may help you out

**Comment by lacostenycoder** [comment]
@jakeonrails wow thank you so much!!!
