### ISSUE TITLE
Spectacle crashing on startup since last update

### ISSUE THREAD

**Issue by alicework** [eczarny/spectacle#698]
Hello,

Since last update the app crashes as soon as it starts

```
Process:         Spectacle [71884]
Path:            /Applications/Divers/Spectacle.app/Contents/MacOS/Spectacle
Identifier:      com.divisiblebyzero.Spectacle
Version:         1.1.2 (659)
Code Type:       X86-64 (Native)
Parent Process:  launchd [212]
Responsible:     Spectacle [71884]
User ID:         501

Date/Time:       2016-12-23 18:27:27.546 +0100
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  30058844-89B4-5FFE-608A-CF3E3AFEAE33


Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
Assertion failed: (tokenCount < maxCountIncludingZeroTerminator - 1), function CUIRenditionKeySetValueForAttribute, file /SourceCache/CoreUI/CoreUI-231.1/CoreTheme/ThemeStorage/CUIThemeRendition.m, line 136.
```

Full Crash log here : 
[crash.txt](https://github.com/eczarny/spectacle/files/671200/crash.txt)

**Comment by abelards** [comment]
I had a look at the error message and found this on StackOverflow[1]:
> To work around this issue, update the deployment target to iOS 8.0 or higher

If I'm reading your config correctly it's `MacOSX.Cocoa`[2]

Perhaps the fix is as simple as a recompile from @eczarny 
I'm willing to spend some time testing, but I haven't set up XCode yet.

If this takes too long you might try to find previous versions @alicework [3]

Cheers to all and thanks for the great tool!

[1] http://stackoverflow.com/questions/39616332/tokencount-maxcountincludingzeroterminator-assertion-osx-10-9#39620599
[2] https://github.com/eczarny/spectacle/blob/329c94963b067f5c292081c6ffff0e6dd68311b3/Spectacle/Resources/Localizations/Base.lproj/Spectacle.xib#L2
[3] https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.1.2.zip

**Comment by alicework** [comment]
Tried installing the linked app [3] but it didn't work, so I uninstalled the app and reinstalled the last version from website, and the app works again.

thank you for your time abelards

**Comment by davereid** [comment]
I had the same issue. Removing the app and downloading a fresh version also worked for me.

OS X 10.9.5
