### ISSUE TITLE
Any plan about Swift version?

### ISSUE THREAD

**Issue by muyexi** [eczarny/spectacle#735]
I'd love to help convert the code base to Swift.

**Comment by eczarny** [comment]
No plans to migrate to Swift. Thanks for offering to help though!

**Comment by rxhanson** [comment]
@eczarny, I'm building what is essentially a Swift version of Spectacle, using MASShortcut. It's not really a fork since it only ended up using the ported window management logic from Spectacle, but I wanted to check with you if you had any thoughts about managing it. Unless you want to take it in under the "Spectacle" brand, I was going to release it as a new separate app with its own public GitHub repo that still abides by the MIT license with your copyright included. I'll clearly state that it is a Swift port using window management logic from Spectacle. Please let me know if you have any thoughts on this. Huge thanks for making this app open source to begin with.

**Comment by rxhanson** [comment]
I built an app in Swift based on Spectacle, and you can find it here: https://github.com/rxhanson/Rectangle. @eczarny, if you have any concerns about it, definitely feel free to let me know - I'm not trying to step on your toes or anything.
@muyexi, I welcome any pull requests if you want to contribute to it!
