### ISSUE TITLE
Remove "icon" bar icon 

### ISSUE THREAD

**Issue by tomasnorre** [eczarny/spectacle#761]
Hi, 

I haven't been able to find where to set this, but I would like to be able to hide the Icon from the menu bar, I prefer my bars as simple as possible. 

Thanks for a cool tool.

**Comment by revelt** [comment]
@tomasnorre maybe the paid app [Bartender](https://www.macbartender.com/) or free-one [Vanilla](http://matthewpalmer.net/vanilla/) would be a solution? I use Bartender myself:

<img width="442" alt="screen shot 2017-05-07 at 18 53 39" src="https://cloud.githubusercontent.com/assets/8344688/25783597/91d2a2cc-3356-11e7-8962-f59f9b2ce7d0.png">

Mind you, "removing bar icon" is not only removing it, it's also creating a substitute app menu page so that the functionality can be accessed. The amount of additional work is quite considerable.

**Comment by cbrnr** [comment]
You can run Spectacle as a background application - this removes the icon in the status bar. To do this, go to Spectacle's preferences, click on the arrow at the bottom right to reveal more options, and then select "Run... as a background application".
