### ISSUE TITLE
Pin window to top (enhancement)

### ISSUE THREAD

**Issue by dpardes** [eczarny/spectacle#845]
I'm often on a Google hangout and need to have other windows open. However, it's disorienting when I accidentally hide the hangout by putting a window on top of it. It would be awesome if I could "pin" a specific window to the top so nothing goes above it (until I stop the pin).

**Comment by ProLoser** [comment]
That feels outside the scope of this app. You should look for other apps that do this, typically using the terms "osx float window". I used to love [afloat](https://github.com/rwu823/afloat) which was all about this functionality and handled additional behavior such as transparency (which would transition to opaque if you focused or hovered over the window) and multi-screen configuration / support. Unfortunately I'm not sure that app is maintained any longer (look at the forks on github) with the latest versions of OSX.

I feel like it would be better to close this issue since what you're describing would greatly bloat the scope of this app and create a huge body of new work and bugs.
